package templates

import (
	"os"
	"path/filepath"
	"text/template"

	"github.com/mccheesy/gdx/internal/tui"
)

// ReadmeData holds the information needed to generate the README.md file.
type ReadmeData struct {
	ProjectName string
	Slug        string
	// IDEs
	Neovide bool
	VSCode  bool
	Rider   bool
	Geany   bool
}

// readmeTemplate is the Go template for the project's README.md file.
const readmeTemplate = `# {{.ProjectName}}

This project was generated by [gdx](https://github.com/mccheesy/gdx).

## Getting Started

This project is set up to run inside a containerized development environment.

### 1. Build the Container Image

First, build the container image using the provided Dockerfile.

` + "```sh" + `
podman build -t {{.Slug}} .
` + "```" + `

*(In the future, you'll be able to run ` + "`gdx build`" + `)*

### 2. Enter the Development Environment

Once the image is built, you can enter the container shell.

` + "```sh" + `
podman run -it --rm -v ./src:/app/src {{.Slug}}
` + "```" + `

*(In the future, you'll be able to run ` + "`gdx enter`" + `)*

### 3. Launching Applications

Your environment includes Godot Mono and the following applications you selected:
{{if .VSCode}}
*   **Visual Studio Code**: It's recommended to install the "Dev Containers" extension on your host and use "Attach to Running Container...".
{{- end}}
{{if .Neovide}}
*   **Neovide**
{{- end}}
{{if .Rider}}
*   **JetBrains Rider** (Note: Requires additional setup for container-based development)
{{- end}}
{{if .Geany}}
*   **Geany**
{{- end}}
`

// GenerateReadme creates a README.md file in the specified project directory.
func GenerateReadme(choices *tui.Choices, projectName, slug, projectDir string) error {
	data := ReadmeData{
		ProjectName: projectName,
		Slug:        slug,
	}

	for _, ide := range choices.IDEs {
		switch ide {
		case "Neovide":
			data.Neovide = true
		case "Visual Studio Code":
			data.VSCode = true
		case "JetBrains Rider":
			data.Rider = true
		case "Geany":
			data.Geany = true
		}
	}

	path := filepath.Join(projectDir, "README.md")
	tmpl, err := template.New("readme").Parse(readmeTemplate)
	if err != nil {
		return err
	}

	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, data)
}
